### PR TITLE
Added GcInventoryTable

### PR DESCRIPTION
**Pull request by SirBarclay**

### CODE REVIEW

**Comment by SirBarclay** [comment]
jeez, gonna d/l src and use IDE from now on xD

**Comment by SirBarclay** [comment]
fucking finally
I'm uploading to github via web browser = hard

**Comment by Bananasft** [comment]
Great that you're helping out, but could you create fewer commits?

One for each class or, since they are related to each other, one for all of them?

Adding 27 commits with similar messages would clutter the commit history :confused:

(Also try to not write commit messages such as "im an idiot")

**Comment by naomichan** [comment]
GcRewardTable, GcRewardTableCategory, GcRewardTableEntry, GcRewardTableItem, GcRewardTableItemList, and GcGenericRewardTableEntry are already implemented on #26.

**Comment by Atvaark** [comment]
These commit can be squashed to a single one (via the git command line), but I don't think that @SirBarclay can do it GitHub.com (only @emoose when merging it).

**Comment by Wadimich** [comment]
I think, that data in INVENTORYTABLE.MBIN shouldn't look like that:
http://pastebin.com/7MLXCk4u
Used build 1.0.53-igayftrb

**Pull request closed without merging**
