### PR TITLE
Add 4 small templates

### PR DESCRIPTION
**Pull request by Elementia**
If this is correct, I can do more.

### CODE REVIEW

**Comment by emoose** [comment]
These seem almost correct, except you forgot to put an NMS(Size) attribute for the arrays in GcBiomeList and GcBiomeListPerStarType. Other than those they seem fine, nice work.

Only problem is that right now arrays of primitives (ints, floats, bools, etc) aren't supported, but there's a pull request (#48) that adds support for them, just waiting on some small issues to be fixed.

Once you've fixed the missing sizes, and that #48 p/r is merged, I'll be happy to merge this in for you :)

**Comment by Elementia** [comment]
Thank you for your answer.
I have fixed the issue with the NMS(Size) I had forgotten.
I'm currently trying to do the TkGeometryData and I have an issue with the List (it says "Invalid list read magic..") but it might be linked with the issue you pointed out.
Also, I find it difficult to understand the structure of jointMirrorPairs and all the attributes I have marked byte[] in TkGeometryData.cs. Is it because it is some kind of binary stream ?

**Comment by emoose** [comment]
>I have an issue with the List (it says "Invalid list read magic..") but it might be linked with the issue you pointed out.

Hmm, just looked into this, it seems like in TkGeometryData / MBIN.PC files lists don't have the normal list magic 01 AA AA AA, instead they have it as 01 00 00 00, very strange. Another MBIN.PC oddity I guess (in addition to the changed DD DD DD DD magic, and data at 0x58)

**Comment by Elementia** [comment]
It seems that the field "Indices16Bit" tells us how to read the list "IndexBuffer".
If its 1 then we should read indexBuffer as a list of 16bit integers
else we should read it as a list of 32bit integers
Also I believe the length of the field "VertexStream" should depends on the field "VertexCount".
How can this type of feature (dynamic length) can be expressed in the template description ?
Do you have exemple of other templates where there is this kind of feature ?

**Comment by emoose** [comment]
VertexStream looks like it's using a normal List&lt;T&gt; field to me, with the number of elements coming just after the element offset, can't really tell what type is being read though.

Not too sure about the IndexBuffer stuff neither, seems like it's using List&lt;int32&gt; though, the code in there is a little wacky but I've seen that sort of thing in a few places, afaik it's just something to do with making sure signed values are read correctly.

Maybe it'll be helpful to look into NMS-View's source code: https://github.com/HugoPeters/NMS-Tools/tree/master/NMS-View/Source

Although that doesn't handle MBIN files properly it works with most model MBINs (though some don't load), it should show how the Vertex/IndexBuffer stuff works though.

**Comment by Elementia** [comment]
I have added some code to handle the float lists, I'm now able to read JointBindings and JointExtends

**Comment by Elementia** [comment]
I've almost finished TkGeometryData. The 3 last fields depends on the value of the previous ones, and I'm not sure how to implements this.
In addition to the "Indices16Bit" field we discussed earlier, we also have the type field of TkVertexLayout that tells us the composition of the data stream (either Vec4 or Vec2). The data stream itself seams to have its own way to encode data, so we might have to write specific code for that.
Tell me if you have ideas about this.
Best regards

**Comment by Elementia** [comment]
The TkGeometryData is now fully mapped. I have started an addon for the 3d software Blender that allow us to load the .exml to visualize and modify it.
There still have work to do on the serialisation of .exml to .mbin in order to import custom made models into the game, but I think it will allow modders to do some interesting stuff :)

**Comment by emoose** [comment]
Nice work, though there's a lot of commits here atm :hushed: Is it possible for you to squash them down into one commit perhaps? (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

Also the methods inside the Extensions class in TkGeometryData.cs should probably be moved to the Shared class inside Shared.cs instead, keeps the template files cleaner.

Other than those two it seems fine, thanks a bunch :+1:

**Comment by Elementia** [comment]
I'm going to sleep a bit. If you want to start on serialization I'll catch up tomorrow.

**Comment by emoose** [comment]
Well I've managed to get it sorta writing fine using a CustomSerialize method, but for the VertexStream it doesn't seem to be writing the exact values, sometimes the exact value is written, but sometimes it looks like the value has been truncated, not really sure why.

I'm using the ToHalf() method from NMS-View to convert the vertex floats back into uint16's, I'd assume that this would work the exact opposite of the ReadHalfLittle() method, which it seems to do for some floats, but for a lot of them it just converts them to -1, or changes the value entirely (eg. 0.7724609 -> 0.7719727)

I've pushed all this up if you want to take a look at it, though I get the feeling the ToHalf() method probably works differently and we'll have to do our own opposite to the ReadHalfLittle() method.

**Pull request merged**
