### PR TITLE
Refactor writing + reading, allowing for primitive type arrays

### PR DESCRIPTION
**Pull request by naomichan**
Tests don't fail, but I don't know if it's working properly with all files.

I tested it with GcRealityManagerData, the data is as expected.

### CODE REVIEW

**Comment by emoose** [comment]
Good stuff, gonna give this a test and hopefully merge it.

**Comment by emoose** [comment]
Hmm, comparing exml output of files from the old deserializer vs this one, it seems that GcRealityManagerData is broken? Might be an alignment issue: http://i.imgur.com/BVpJvEq.png

Left side is the old deserializer, right side is the new one. Strange that the new one also seems to be getting values that were missing in the old one.

Other than that all the other files seem to match up fine.

**Comment by naomichan** [comment]
I'll look at those two.

**Comment by emoose** [comment]
Managed to fix it, was just a stray EmptyNode inside GcRealityManagerData, removed that and now its deserializing it fine, even gets more values than the old one, nice work :+1:

**Pull request merged**
